# Generated by Django 2.2.10 on 2021-05-10 10:21

import app3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, validators=[app3.models.validate_date])),
                ('cat_image', models.FileField(upload_to='img/%y')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
